# easy_admin:
#     entities:
#         Etudiant:
#         class: ['App\Entity\Filiere','App\Entity\Archive','App\Entity\User','App\Entity\Etudiant']
#         form:
#             fields:
#                 - {property: 'email'}
#                 - {property: 'roles'}
#                 - {property: 'password'}
#                 - {property: 'confirmepassword'}
#                 - {property: 'firstname'}
#                 - {property: 'niveau'}
                


          
